#!/usr/bin/env sh

keys=$(gpg --list-keys | grep uid | cut -d "<" -f2 | cut -d ">" -f1)
adir="$HOME/.local/share/file-manager/actions"
items="ItemsList="

# Delete uid entries
rm "$adir/uid_"*".desktop"

# Write uid entries
for i in $keys; do
	items="${items}uid_$i;"
	cat > "$adir/uid_$i.desktop" <<- EOT
		[Desktop Entry]
		Name=$i
		Tooltip=Encrypt for $i
		Icon=keys
		Profiles=on_file;

		[X-Action-Profile on_file]
		MimeTypes=all/allfiles;
		Exec=gpg --encrypt --recipient $i %f
	EOT
done

# Group uid entries
cat > "$adir/gpg-actions-menu.desktop" <<- EOF
	[Desktop Entry]
	Type=Menu
	Name=Encrypt for...
	Tooltip=Encrypt and sign file for the specified user
	Icon=gnupg
	${items}SEPARATOR;gpg-actions-refresh;
EOF
